### ISSUE TITLE
Enhancement - Add Corporate Proxy Support

### ISSUE THREAD

**Issue by Mrassimo** [Mrassimo/datapilot#39]
### **Description**
Corporate environments often require proxy configuration for internet access. DataPilot should support standard proxy protocols for enterprise deployment.

### **Current State**
- Package.json includes "proxy-friendly" keyword
- No explicit proxy configuration options
- May fail in corporate environments with mandatory proxies

#### **Command Line Options**
```bash
datapilot --proxy http://proxy.company.com:8080 all data.csv
datapilot --proxy-auth user:password all data.csv
datapilot --no-proxy all data.csv  # Bypass proxy detection
```

#### **Environment Variable Support**
```bash
export HTTP_PROXY=http://proxy.company.com:8080
export HTTPS_PROXY=http://proxy.company.com:8080  
export NO_PROXY=localhost,127.0.0.1
datapilot all data.csv
```

#### **Configuration File Support**
```yaml
# .datapilotrc
proxy:
  http: "http://proxy.company.com:8080"
  https: "http://proxy.company.com:8080"
  auth: "user:password"
  bypass: ["localhost", "*.internal.com"]
```

### **Enterprise Requirements**
- NTLM/Kerberos authentication support
- Proxy auto-detection
- SSL certificate validation options
- Timeout configuration

### **Implementation Notes**
Since DataPilot processes files locally and doesn't make external HTTP requests, this may primarily be needed for:
- Future features that fetch external data
- Package installation/updates
- Telemetry (if added)

### **Priority**
Medium - Required for some enterprise deployments where proxy is mandatory
